import Head from 'next/head'

import {
  ContainerWithUpperBar,
  Content,
  IndexPageContainer,
} from '@/appSlice/pagesStyles/index.styles'
import BannerStreams from '@/widgets/BannerStreams/ui'
import FromChannelsYouFollow from '@/widgets/FromChannelsYouFollow/ui'
import LiveChannels from '@/widgets/LiveChannels/ui'
import Sidebar from '@/widgets/Sidebar/ui'
import UpperBar from '@/widgets/UpperBar/ui'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexPageContainer>
        <Sidebar />
        <ContainerWithUpperBar>
          <UpperBar />
          <BannerStreams />
          <Content>
            <LiveChannels />
            <FromChannelsYouFollow />
          </Content>
        </ContainerWithUpperBar>
      </IndexPageContainer>
    </>
  )
}

export default Home
