import Head from 'next/head'

import { IndexPageContainer } from '@/appSlice/pagesStyles/index.styles'
import Sidebar from '@/widgets/Sidebar/ui'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexPageContainer>
        <Sidebar />
      </IndexPageContainer>
    </>
  )
}

export default Home
