import Head from 'next/head'

import {
  ContainerWithUpperBar,
  Content,
  TrendingPageContainer,
} from '@/appSlice/pagesStyles/trending.styles'
import Sidebar from '@/widgets/Sidebar'
import TopTrendingStreams from '@/widgets/TopTrendingStreams/ui'
import TrendingBanners from '@/widgets/TrendingBanners/ui'
import UpperBar from '@/widgets/UpperBar'

const Trending = () => {
  return (
    <>
      <Head>
        <title>Unity Gaming | Trending</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TrendingPageContainer>
        <Sidebar />
        <ContainerWithUpperBar>
          <UpperBar />
          <Content>
            <TrendingBanners />
            <TopTrendingStreams />
          </Content>
        </ContainerWithUpperBar>
      </TrendingPageContainer>
    </>
  )
}

export default Trending
